# Generated by Django 5.2.1 on 2025-05-17 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jahadf.item')),
                ('cname', models.CharField(default='Laptop', max_length=30)),
            ],
            bases=('jahadf.item',),
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jahadf.item')),
                ('cname', models.CharField(default='Mobile', max_length=30)),
            ],
            bases=('jahadf.item',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jahadf.item')),
                ('cname', models.CharField(default='Monitor', max_length=30)),
            ],
            bases=('jahadf.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jahadf.market'),
        ),
    ]
