# Generated by Django 5.2.1 on 2025-05-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jahadf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='model',
        ),
    ]
